### ISSUE TITLE
קולות קוראים כפולים

### ISSUE THREAD

**Issue by maryLoi** [OpenBudget/BudgetKey#412]
![image](https://user-images.githubusercontent.com/8996235/69378693-92395200-0cb7-11ea-86d8-275b84a9e714.png)

https://next.obudget.org/s/?q=%D7%91%D7%A7%D7%A9%D7%95%D7%AA%20%D7%9C%D7%AA%D7%9E%D7%99%D7%9B%D7%94%20%D7%9E%D7%AA%D7%A7%D7%A6%D7%99%D7%91%20%D7%9E%D7%A9%D7%A8%D7%93%20%D7%94%D7%AA%D7%A8%D7%91%D7%95%D7%AA&dd=supports&range=last_month&lang=he&kind=calls_for_bids

**Comment by akariv** [comment]
Since we don't have a unique id of each of these items that we're scraping, we're auto-generating one from a combination of their name, description and dates.
This means that if an item changes in some way, it will usually appear as a new item and not as a replacement for the old one (as we can't tell if it's the same one that changed or really a new one).
In this case, while the items' title is identical, their descriptions were actually slightly different.

I added some pruning mechanism to remove items which are not visible any more from the search results - this way we'll only show items that are currently available in the source and avoid such duplications.
